### ISSUE TITLE
Test URLs in addon manifest failing because of self-signed certificate

### ISSUE THREAD

**Issue by beberlei** [heroku/kensa#102]
`kensa test` should not fail, when the test urls are ssl and use self-signed certificates. This wasn't the case with an older version of Kensa, but the latest one starts failing:

```
Testing POST /api/heroku/resources
  Check response/var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:445:in `rescue in transmit': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (RestClient::SSLCertificateNotVerified)
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:350:in `transmit'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:67:in `post'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/http.rb:39:in `request'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/http.rb:13:in `post'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:369:in `block in call!'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:29:in `check'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:355:in `call!'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:61:in `block in to_proc'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:38:in `instance_eval'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:38:in `run'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:573:in `call!'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/check.rb:50:in `call'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/client.rb:159:in `block in run_check'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/client.rb:156:in `each'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/client.rb:156:in `run_check'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/client.rb:54:in `test'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/lib/heroku/kensa/client.rb:22:in `run!'
	from /var/lib/gems/2.1.0/gems/kensa-3.0.0/bin/kensa:17:in `<top (required)>'
	from /usr/local/bin/kensa:23:in `load'
	from /usr/local/bin/kensa:23:in `<main>'
```

**Comment by cdwort** [comment]
Hey @heroku/add-ons 

This looks like RestClient erroring out. We upgraded RestClient with the bump from `2.4.2` to `2.4.3`
on `Tue Nov 24 15:10:47 2015 -0800`. RestClient went [from 1.6.8 to 1.8.](https://github.com/rest-client/rest-client/compare/v1.6.8...v1.8.0) which includes changes to begin enforcing SSL Cert checks.

Looks like we'll want to update Kensa to allow invalid certs when testing. There's an option `verify_ssl: false` that we can [pass in here](https://github.com/heroku/kensa/blob/master/lib/heroku/kensa/http.rb#L39) that should do it if Http#request is only used for tests. Otherwise, we'll need to make Http configurable.

**Comment by mathias** [comment]
As a workaround, does it work to specify your test URLs without "https"? (If you can access them without SSL, but I am guessing they're running on localhost?)

**Comment by cdwort** [comment]
Hey @jeremykendall

You could try @mathias' ^^ workaround in the mean time if you don't want to keep your custom Kensa change around.

**Comment by cdwort** [comment]
Hey @heroku/add-ons 

It looks like the solution I mentioned above, setting `verify_ssl: false` on [HTTP](https://github.com/heroku/kensa/blob/master/lib/heroku/kensa/http.rb#L39) may be our main option.

`HTTP` appears to be only used in the Kensa checks, not in the actual posting of manifests. @jeremykendall independently came to that solution and says that it fixes this problem.

From my point of view, I'm fine this change so long as we update the `HTTP` class to be namespaced to something like `Kensa::Check` or be named `HTTPForTests`. So long as it's clear you shouldn't use this for real things, I'm fine with it. 

I would obviously appreciate a second confirmation that `HTTP` is only used for checks.
