### ISSUE TITLE
kensa run all fails with return code 32512

### ISSUE THREAD

**Issue by jasonwalsh** [heroku/kensa#113]
I'm using kensa for my integration tests for the Heroku Add-on Partner API, and it's failing with a non-zero status code when running `kensa run all`. The output from the command is:

```
Starting all...

 [FAIL]
    run exited abnormally, expected 0, got 32512
```

I am provisioning the resource synchronously and using the documentation described [here](https://devcenter.heroku.com/articles/add-on-partner-api-reference#synchronous-provisioning).

The error appears to be happening [here](https://github.com/heroku/kensa/blob/master/lib/heroku/kensa/check.rb#L590-L591).

Any ideas?

**Comment by mathias** [comment]
Hello, 

Please try out our new replacement for Kensa, https://github.com/heroku/heroku-cli-addons-admin

It won't run tests like Kensa does, but you might prefer to write those acceptance tests in your framework's test suite so that they are under continuous integration, etc.

Thanks!

**Comment by jasonwalsh** [comment]
Thanks @mathias. Closing this issue.
