### ISSUE TITLE
Kensa doesn't send syslog_token

### ISSUE THREAD

**Issue by mheffner** [heroku/kensa#65]
According to the documentation here: https://devcenter.heroku.com/articles/accessing-app-logs

..adding a require on 'syslog_drain' to your manifest should send a `syslog_token` in the provisioning request.

As of kensa version 1.4.6, I don't see this in the payload. Am I missing something?

**Comment by wpc** [comment]
I believe it should be "log_drain_token" instead of "syslog_token", and it is included in the provision requests from kensa.

**Comment by mattreduce** [comment]
What @wpc said is correct, and we've since updated that Dev Center article. Thanks for reporting! :)
