### ISSUE TITLE
Not clear on how to update an existing addon manifest

### ISSUE THREAD

**Issue by wpc** [heroku/kensa#90]
I am trying to use kensa push to update manifest for my addon and always got error:
````
% kensa push
FAILED: Can't revise stale manifest; please base your changes on the latest manifest
````
It's pretty clueless and cost me long time found for update it need a "$base" field to identify what's the update based on.  I hope there are at least some document there guiding me.

-- wpc

**Comment by bjeanes** [comment]
@wpc Make sure you have the latest `kensa` and then do an initial `kensa pull` and make your changes to that. The newest `kensa` should automatically pull the modified version after a `push` so explicit pulls shouldn't be necessary. However, older `kensa` versions should explicitly ask you to upgrade, which makes me think you are on the latest. If the manifest was updated by someone else or on a different computer or by us, that could be the cause.

**Comment by wpc** [comment]
I did change the manifest through provider's page, but it did not save correctly. Then when I switch to kensa push it always give me this error. Now I am clear I will close this issue.

**Comment by bjeanes** [comment]
> I did change the manifest through provider's page, but it did not save correctly.

Any more details here would be appreciated. I've had others report this but I can't replicate. Which browser and OS are you using? May be some JS nonsense going on. Did the `$base` identifier change? If so, it's saving a new version but not absorbing the actual modifications...

**Comment by wpc** [comment]
Mac OSX 10.9.5, neither Chrome v43 nor Firefox 39.0 works. It reports save successfully but changes not persisted. $base not changed. And no previous version generated on the UI.

**Comment by bjeanes** [comment]
@wpc thanks. Tracked down the issue and web-based manifest editing seems to work again.
