### ISSUE TITLE
tests not matching docs: syslog_drain_url

### ISSUE THREAD

**Issue by garth0323** [heroku/kensa#93]
Tests look for: response["syslog_drain_url"]

in  kensa test:  Check syslog_drain_url is returned if required

but docs say expected response is 'log_drain_url' on:

https://devcenter.heroku.com/articles/accessing-app-logs

**Comment by bjeanes** [comment]
Hi @garth0323. Both identifiers are valid. The docs' recommendation is probably better to follow, but feel free to use `syslog_drain_url` to get the Kensa test passing for now, and we'll try to update it soon to reflect the docs. Thanks.
